version: "3"

services:
  project:
    container_name: gcalendar
    image: calendar
    build: .
    depends_on:
      - redis
    command: python3 app.py flask run
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  redis: