version: "3"

services:
  project:
    container_name: gcalendar
    image: calendar
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    command: python3 app.py flask run
    ports:
      - "5000:5000"
    volumes:
      - .:/project
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  redis: